### Arrays, Indexing, and Slicing

In [1]:
import numpy as np

In [2]:
# Create a 1D array of 5 zeros
array_1d = np.zeros(5)
print("1D Array:\n", array_1d)
print("Shape:", array_1d.shape)

1D Array:
 [0. 0. 0. 0. 0.]
Shape: (5,)


In [3]:
# Create a 2D array (3 rows, 4 columns) of all ones
array_2d = np.ones((3, 4))
print("\n2D Array:\n", array_2d)
print("Shape:", array_2d.shape)


2D Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)


In [4]:
# Create a 3D array (2 matrices, each 3 rows by 3 columns) filled with random normal numbers
array_3d = np.random.randn(2, 3, 3)
print("\n3D Array:\n", array_3d)
print("Shape:", array_3d.shape)



3D Array:
 [[[-0.04963087  0.61440796 -0.74345768]
  [-0.9727416   1.94027448  0.68781049]
  [-1.1262824  -0.31037276  0.35750703]]

 [[ 1.09874337 -1.44276155  1.45482787]
  [ 0.7059175   0.09967801  1.11052044]
  [-0.35559994  1.1530578  -0.38790033]]]
Shape: (2, 3, 3)


In [10]:
# Generate a specific 2D matrix for practice
matrix = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

In [11]:
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
# 2. Slice out the first two rows and the last two columns
# Syntax is [start_row:end_row, start_col:end_col] (remember, end index is exclusive)
sub_matrix = matrix[0:2, 1:3]
print("Extracted Sub-matrix:\n", sub_matrix)

Extracted Sub-matrix:
 [[20 30]
 [50 60]]


In [14]:
# 3. Pull out the entire 3rd row
third_row = matrix[2, :]
print (third_row)

[70 80 90]


###:  My Day 1 excertice