### Arrays, Indexing, and Slicing

In [1]:
import numpy as np

In [2]:
# Create a 1D array of 5 zeros
array_1d = np.zeros(5)
print("1D Array:\n", array_1d)
print("Shape:", array_1d.shape)

1D Array:
 [0. 0. 0. 0. 0.]
Shape: (5,)


In [3]:
# Create a 2D array (3 rows, 4 columns) of all ones
array_2d = np.ones((3, 4))
print("\n2D Array:\n", array_2d)
print("Shape:", array_2d.shape)


2D Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)


In [4]:
# Create a 3D array (2 matrices, each 3 rows by 3 columns) filled with random normal numbers
array_3d = np.random.randn(2, 3, 3)
print("\n3D Array:\n", array_3d)
print("Shape:", array_3d.shape)



3D Array:
 [[[-0.04963087  0.61440796 -0.74345768]
  [-0.9727416   1.94027448  0.68781049]
  [-1.1262824  -0.31037276  0.35750703]]

 [[ 1.09874337 -1.44276155  1.45482787]
  [ 0.7059175   0.09967801  1.11052044]
  [-0.35559994  1.1530578  -0.38790033]]]
Shape: (2, 3, 3)


In [10]:
# Generate a specific 2D matrix for practice
matrix = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

In [11]:
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
# 2. Slice out the first two rows and the last two columns
# Syntax is [start_row:end_row, start_col:end_col] (remember, end index is exclusive)
sub_matrix = matrix[0:2, 1:3]
print("Extracted Sub-matrix:\n", sub_matrix)

Extracted Sub-matrix:
 [[20 30]
 [50 60]]


In [14]:
# 3. Pull out the entire 3rd row
third_row = matrix[2, :]
print (third_row)

[70 80 90]


###:  My Day 1 excertice

In [15]:
# Create a massive 1000x1000 matrix filled with random numbers
large_matrix = np.random.randn(1000, 1000)


In [16]:
# 1. Multiply the ENTIRE matrix by a scalar (Broadcasting a single number across 1 million cells)
scaled_matrix = large_matrix * 5

In [20]:
print (large_matrix[0,1])

0.2301185045611904


In [21]:
print (scaled_matrix[0,1])

1.150592522805952


In [22]:
# 2. Add two matrices of identical shapes together instantly
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_sum = matrix_a + matrix_b
print("Element-wise sum:\n", matrix_sum)

Element-wise sum:
 [[ 6  8]
 [10 12]]


In [23]:
# Generate an array of integers from 1 to 10
data = np.array([1, 8, 3, 12, 5, 7, 2, 14, 9, 4])

In [24]:
# Step 1: Create the boolean mask condition
mask = data > 5
print("The Boolean Mask Array:\n", mask)

The Boolean Mask Array:
 [False  True False  True False  True False  True  True False]


In [25]:
# Step 2: Pass the mask back into the data array to filter out numbers instantly
filtered_data = data[mask]
print("\nFiltered Results (Only numbers > 5):\n", filtered_data)


Filtered Results (Only numbers > 5):
 [ 8 12  7 14  9]


In [26]:
# Advanced: Replace specific numbers matching a condition
# Change any number less than 5 to a zero placeholder instantly
data[data < 5] = 0
print("\nData after in-place replacement:\n", data)


Data after in-place replacement:
 [ 0  8  0 12  5  7  0 14  9  0]


# My exercise 

In [ ]:
##Task 1.1: Create a 1D array containing exactly 10 zeros. Change the 5th element (index 4) to have a value of 99. Print the array.

In [29]:
import numpy as np
data =np.zeros(10)
print ("before array:\n", data)
data[4]=99
print ("After array:\n", data)

before array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After array:
 [ 0.  0.  0.  0. 99.  0.  0.  0.  0.  0.]


##Task 1.2: Create a 2D array (matrix) with a shape of (5, 5) where every single element is initialized to 1.

In [42]:
import numpy as np
TwoD_data = np.ones((5,5,2))
print ("before array:\n", TwoD_data)
TwoD_data.ndim
TwoD_data.shape

before array:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


(5, 5, 2)

##: Task 1.3: Create a 3D array with a shape of (2, 3, 4) filled with random numbers drawn from a normal distribution (np.random.randn).

In [49]:
import numpy as np
ThreeD_data = np.random.randn(2,3,4)
print ("before array:\n", ThreeD_data)
ThreeD_data.shape
ThreeD_data.ndim
ThreeD_data.size

before array:
 [[[ 2.17558925  1.49699551  0.86698158 -0.467396  ]
  [ 0.75227738 -0.56249986 -1.25677527 -0.31341002]
  [ 0.66544972 -0.91444329  0.61053067  0.12557141]]

 [[ 0.02536115  0.66437464  0.52273646  0.93415437]
  [-1.73152563  1.02426079  0.20915553 -0.85919187]
  [-0.03376591  0.19760042  1.79850426 -0.15818868]]]


24

##:Task 2.1 (Scalar Stretch): Create a (3, 3) matrix containing numbers from 1 to 9. Multiply the entire matrix by 10 in a single line of code.

In [53]:
import numpy as np
matrix = np.arange(1,10,1).reshape(3,3)
print ("Before:\n", matrix)
scalar =10
matrix = matrix * scalar
print ("After:\n", matrix)

Before:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


## Task 2.2 (Matrix Addition): Create two separate (2, 4) matrices filled with random integers. Add them together so each overlapping cell updates its sum.

In [57]:
import numpy as np
# 1. Create the first (2, 4) matrix filled with random integers between 1 and 10
# (low=1, high=11 means it includes numbers from 1 to 10. size=(2,4) sets the shape)
matrix_a = np.random.randint(low=1, high=11, size=(2, 4))

# 2. Create the second (2, 4) matrix filled with random integers between 1 and 10
matrix_b = np.random.randint(low=1, high=11, size=(2, 4))

# 3. Add them together (NumPy automatically pairs up overlapping cells)
matrix_sum = matrix_a + matrix_b

# 4. Print the results to see the math in action
print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nResulting Sum Matrix (A + B):\n", matrix_sum)

Matrix A:
 [[ 6  7  4  2]
 [10  8  6  9]]

Matrix B:
 [[10 10  7  6]
 [ 2  9  7  9]]

Resulting Sum Matrix (A + B):
 [[16 17 11  8]
 [12 17 13 18]]


##: Task 2.3 (Broadcasting Challenge): * Create a 2D matrix of shape (4, 3) filled with ones.

Create a 1D array of shape (3,) containing the numbers [10, 20, 30].

Add the 1D array to the 2D matrix. Observe how NumPy automatically "stretches" the row across all 4 rows of the matrix.

In [59]:
import numpy as np
matrix_a =np.ones((4,3))
matrix_b =np.array([10, 20, 30]).reshape(3,)
matrix_c = matrix_a + matrix_b

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nResulting Sum Matrix (A + B):\n", matrix_c)

Matrix A:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matrix B:
 [10 20 30]

Resulting Sum Matrix (A + B):
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


##: ask 3.1 (Basic Sieve): Create a 1D array containing the following random numbers: [12, 4, 7, 19, 2, 18, 5, 14, 8, 1].

Write a conditional statement to extract only the numbers that are strictly greater than 10.

In [64]:
import numpy as np
data = np.array([12, 4, 7, 19, 2, 18, 5, 14, 8, 1])
selecteddata = data[data > 10]
print("Before:\n", data)
print("\nAfter:\n", selecteddata )

Before:
 [12  4  7 19  2 18  5 14  8  1]

After:
 [12 19 18 14]


##: Task 3.2 (Even Number Extraction): Using the same array from Task 3.1, use the modulo operator (% 2 == 0) inside a boolean mask to filter and return only the even numbers.

In [65]:
import numpy as np
data = np.array([12, 4, 7, 19, 2, 18, 5, 14, 8, 1])
selecteddata = data[data % 2 == 0]
print("Before:\n", data)
print("\nAfter:\n", selecteddata )

Before:
 [12  4  7 19  2 18  5 14  8  1]

After:
 [12  4  2 18 14  8]


##: Task 3.3 (Data Clean-up / Boundary Cap): Create a (4, 4) matrix of random numbers between -5 and 5. In a single line of code, find every single negative number and replace it instantly with 0. (This mimics a critical deep learning function called a ReLU activation layer!).

In [66]:
import numpy as np
matrix_a = np.random.randint(low=-5, high=5, size=(4, 4))

print("Before\n", matrix_a)

matrix_a [matrix_a < 0] = 0

print("After\n", matrix_a)

Before
 [[-2 -5  3  2]
 [-5  2 -1  1]
 [-4  1 -5  2]
 [-4 -3  2 -2]]
After
 [[0 0 3 2]
 [0 2 0 1]
 [0 1 0 2]
 [0 0 2 0]]


##: The Performance Verification Challenge

In [67]:
import time
import numpy as np

# Create a large array of 1 million numbers
massive_array = np.arange(1_000_000)

# Method A: Traditional Python Loop
start_time = time.time()
loop_result = []
for x in massive_array:
    loop_result.append(x * 2)
print(f"Python Loop Time: {time.time() - start_time:.5f} seconds")

# Method B: NumPy Vectorization
start_time = time.time()
vector_result = massive_array * 2
print(f"NumPy Vectorized Time: {time.time() - start_time:.5f} seconds")

Python Loop Time: 0.35592 seconds
NumPy Vectorized Time: 0.00425 seconds
